import 'package:flutter/material.dart';

import '../../../../core/theme/app_theme.dart';
import '../../../calendar/domain/entities/free_time_slot.dart';
import '../../domain/entities/workout_plan.dart';

class ScheduledWorkoutItem {
  ScheduledWorkoutItem({
    required this.id,
    required this.name,
    required this.durationMinutes,
    required this.caloriesBurned,
    this.isCompleted = false,
    this.isAutoGenerated = false,
  });

  final String id;
  final String name;
  final int durationMinutes;
  final int caloriesBurned;
  bool isCompleted;
  final bool isAutoGenerated;

  ScheduledWorkoutItem copyWith({
    String? name,
    int? durationMinutes,
    int? caloriesBurned,
    bool? isCompleted,
  }) {
    return ScheduledWorkoutItem(
      id: id,
      name: name ?? this.name,
      durationMinutes: durationMinutes ?? this.durationMinutes,
      caloriesBurned: caloriesBurned ?? this.caloriesBurned,
      isCompleted: isCompleted ?? this.isCompleted,
      isAutoGenerated: isAutoGenerated,
    );
  }
}

class DayTimeSlot {
  DayTimeSlot({
    required this.id,
    required this.startTime,
    required this.endTime,
    required this.availableDuration,
    required this.workouts,
  });

  final String id;
  final String startTime;
  final String endTime;
  final int availableDuration;
  List<ScheduledWorkoutItem> workouts;

  int get usedDuration => workouts.fold(0, (sum, w) => sum + w.durationMinutes);
  int get remainingDuration => availableDuration - usedDuration;

  DayTimeSlot copyWith({
    List<ScheduledWorkoutItem>? workouts,
  }) {
    return DayTimeSlot(
      id: id,
      startTime: startTime,
      endTime: endTime,
      availableDuration: availableDuration,
      workouts: workouts ?? this.workouts,
    );
  }
}

class WorkoutPlanPage extends StatefulWidget {
  const WorkoutPlanPage({
    required this.freeTimeSlots,
    required this.workoutSuggestions,
    required this.scheduledWorkout,
    required this.selectedSlot,
    required this.calendarEvents,
    required this.upcomingPlans,
    required this.onWorkoutScheduled,
    required this.onWorkoutCompleted,
    required this.onSelectSlot,
    super.key,
  });

  // Maintaining signature parameters for compatibility, but we can override inside state
  final List<FreeTimeSlot> freeTimeSlots;
  final List<WorkoutPlan> workoutSuggestions;
  final WorkoutPlan? scheduledWorkout;
  final FreeTimeSlot? selectedSlot;
  final dynamic calendarEvents;
  final dynamic upcomingPlans;
  final ValueChanged<WorkoutPlan> onWorkoutScheduled;
  final ValueChanged<WorkoutPlan> onWorkoutCompleted;
  final ValueChanged<FreeTimeSlot?> onSelectSlot;

  @override
  State<WorkoutPlanPage> createState() => _WorkoutPlanPageState();
}

class _WorkoutPlanPageState extends State<WorkoutPlanPage> {
  final List<String> _weekdays = ['Thứ 2', 'Thứ 3', 'Thứ 4', 'Thứ 5', 'Thứ 6', 'Thứ 7', 'Chủ Nhật'];
  String _selectedDay = 'Thứ 2';
  int _minRequiredTime = 60; // Minutes

  // Day to slots mapping state
  late Map<String, List<DayTimeSlot>> _daySlotsMap;

  // Preset workouts list
  final List<Map<String, dynamic>> _presets = const [
    {'name': 'Chạy bộ sảng khoái 🏃‍♂️', 'duration': 30, 'calories': 220},
    {'name': 'Đạp xe dạo hồ 🚴', 'duration': 45, 'calories': 180},
    {'name': 'Yoga dẻo dai 🧘', 'duration': 20, 'calories': 80},
    {'name': 'Tập Gym Cardio 🏋️‍♂️', 'duration': 45, 'calories': 300},
    {'name': 'Nhảy dây đốt mỡ ⚡', 'duration': 15, 'calories': 150},
    {'name': 'Bơi sải tự do 🏊‍♂️', 'duration': 40, 'calories': 250}
  ];

  @override
  void initState() {
    super.initState();
    _daySlotsMap = {
      'Thứ 2': [
        DayTimeSlot(
          id: 'slot_2_1',
          startTime: '06:00',
          endTime: '07:30',
          availableDuration: 90,
          workouts: [
            ScheduledWorkoutItem(
              id: 'w_2_1_1',
              name: 'Chạy bộ sáng bờ hồ 🏃‍♂️',
              durationMinutes: 30,
              caloriesBurned: 220,
              isCompleted: false,
            )
          ],
        ),
        DayTimeSlot(
          id: 'slot_2_2',
          startTime: '17:30',
          endTime: '19:30',
          availableDuration: 120,
          workouts: [],
        ),
      ],
      'Thứ 3': [
        DayTimeSlot(id: 'slot_3_1', startTime: '06:30', endTime: '07:30', availableDuration: 60, workouts: []),
        DayTimeSlot(
          id: 'slot_3_2',
          startTime: '16:45',
          endTime: '18:45',
          availableDuration: 120,
          workouts: [
            ScheduledWorkoutItem(
              id: 'w_3_2_1',
              name: 'Bơi tự do giải stress 🏊‍♂️',
              durationMinutes: 45,
              caloriesBurned: 280,
              isCompleted: true,
            )
          ],
        ),
      ],
      'Thứ 4': [
        DayTimeSlot(
          id: 'slot_4_1',
          startTime: '06:15',
          endTime: '08:15',
          availableDuration: 120,
          workouts: [
            ScheduledWorkoutItem(
              id: 'w_4_1_1',
              name: 'Yoga tĩnh tâm 🧘',
              durationMinutes: 45,
              caloriesBurned: 150,
              isAutoGenerated: true,
            )
          ],
        ),
        DayTimeSlot(id: 'slot_4_2', startTime: '18:00', endTime: '19:30', availableDuration: 90, workouts: []),
      ],
      'Thứ 5': [
        DayTimeSlot(
          id: 'slot_5_1',
          startTime: '17:00',
          endTime: '19:00',
          availableDuration: 120,
          workouts: [
            ScheduledWorkoutItem(
              id: 'w_5_1_1',
              name: 'Đạp xe dạo quanh phố 🚴',
              durationMinutes: 45,
              caloriesBurned: 180,
            )
          ],
        ),
      ],
      'Thứ 6': [
        DayTimeSlot(
          id: 'slot_6_1',
          startTime: '17:30',
          endTime: '19:30',
          availableDuration: 120,
          workouts: [
            ScheduledWorkoutItem(
              id: 'w_6_1_1',
              name: 'HIIT bứt cơ nhanh 🔥',
              durationMinutes: 45,
              caloriesBurned: 350,
              isAutoGenerated: true,
            )
          ],
        ),
      ],
      'Thứ 7': [
        DayTimeSlot(
          id: 'slot_7_1',
          startTime: '15:00',
          endTime: '18:00',
          availableDuration: 180,
          workouts: [
            ScheduledWorkoutItem(
              id: 'w_7_1_1',
              name: 'Đá bóng giao lưu ⚽',
              durationMinutes: 90,
              caloriesBurned: 500,
            )
          ],
        ),
      ],
      'Chủ Nhật': [
        DayTimeSlot(id: 'slot_8_1', startTime: '07:00', endTime: '09:30', availableDuration: 150, workouts: []),
      ],
    };
  }

  int get _totalWorkoutTime {
    final slots = _daySlotsMap[_selectedDay] ?? [];
    return slots.fold(0, (sum, slot) => sum + slot.usedDuration);
  }

  bool get _isGoalAchieved => _totalWorkoutTime >= _minRequiredTime;

  // Auto scheduler trigger
  void _triggerAutoSchedule() {
    final slots = _daySlotsMap[_selectedDay] ?? [];
    int currentTotal = _totalWorkoutTime;
    final goal = _minRequiredTime;

    int timeNeeded = goal - currentTotal;
    if (timeNeeded <= 0) {
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(content: Text('Chỉ tiêu đã hoàn thành xuất sắc! 🎉 ($currentTotal/$goal phút)')),
      );
      return;
    }

    final tempSlots = slots.map((s) => s.copyWith(workouts: List<ScheduledWorkoutItem>.from(s.workouts))).toList();
    bool isProgressMade = true;
    int itemsAdded = 0;
    int minutesAdded = 0;

    while (currentTotal < goal && isProgressMade) {
      isProgressMade = false;
      for (int i = 0; i < tempSlots.length; i++) {
        final slot = tempSlots[i];
        final remainingSpace = slot.remainingDuration;

        if (remainingSpace > 0) {
          final fitPresets = _presets.where((p) => (p['duration'] as int) <= remainingSpace).toList();
          if (fitPresets.isNotEmpty) {
            final selected = (fitPresets..shuffle()).first;
            final duration = selected['duration'] as int;
            final name = selected['name'] as String;
            final calories = selected['calories'] as int;

            final newItem = ScheduledWorkoutItem(
              id: 'auto_${DateTime.now().microsecondsSinceEpoch}',
              name: name,
              durationMinutes: duration,
              caloriesBurned: calories,
              isAutoGenerated: true,
            );

            tempSlots[i].workouts.add(newItem);
            currentTotal += duration;
            minutesAdded += duration;
            itemsAdded++;
            isProgressMade = true;

            // Trigger callback for SQLite tracking compatibility
            widget.onWorkoutScheduled(
              WorkoutPlan(
                id: newItem.id,
                title: name,
                durationMinutes: duration,
                difficulty: 'Auto',
                equipment: 'None',
                estimatedCaloriesBurned: calories,
                exercises: [name],
                tags: const [],
                isScheduled: true,
              ),
            );

            if (currentTotal >= goal) break;
          }
        }
      }
    }

    if (itemsAdded > 0) {
      setState(() {
        _daySlotsMap[_selectedDay] = tempSlots;
      });
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(content: Text('Đã xếp thêm $itemsAdded môn (+ $minutesAdded phút) vào khung giờ trống! 🤖⚡')),
      );
    } else {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text('Các khung giờ rảnh đều đã kín! Hãy tạo thêm khung rảnh mới. ⚠️')),
      );
    }
  }

  void _showAddCustomSlotDialog() {
    final startCtrl = TextEditingController(text: '17:00');
    final endCtrl = TextEditingController(text: '19:00');
    final formKey = GlobalKey<FormState>();

    showDialog<void>(
      context: context,
      builder: (context) {
        return AlertDialog(
          title: const Text('Thêm khung giờ rảnh 📅', style: TextStyle(fontWeight: FontWeight.bold)),
          content: Form(
            key: formKey,
            child: Column(
              mainAxisSize: MainAxisSize.min,
              children: [
                TextFormField(
                  controller: startCtrl,
                  decoration: const InputDecoration(labelText: 'Giờ bắt đầu (HH:mm)'),
                  validator: (v) => v == null || v.isEmpty ? 'Nhập giờ bắt đầu' : null,
                ),
                const SizedBox(height: 8),
                TextFormField(
                  controller: endCtrl,
                  decoration: const InputDecoration(labelText: 'Giờ kết thúc (HH:mm)'),
                  validator: (v) => v == null || v.isEmpty ? 'Nhập giờ kết thúc' : null,
                ),
              ],
            ),
          ),
          actions: [
            TextButton(
              onPressed: () => Navigator.of(context).pop(),
              child: const Text('Huỷ', style: TextStyle(color: AppTheme.vibrantTextMedium)),
            ),
            ElevatedButton(
              onPressed: () {
                if (formKey.currentState!.validate()) {
                  final startStr = startCtrl.text.split(':');
                  final endStr = endCtrl.text.split(':');
                  if (startStr.length == 2 && endStr.length == 2) {
                    final startH = int.parse(startStr[0]);
                    final startM = int.parse(startStr[1]);
                    final endH = int.parse(endStr[0]);
                    final endM = int.parse(endStr[1]);
                    final duration = (endH * 60 + endM) - (startH * 60 + startM);
                    if (duration <= 0) {
                      ScaffoldMessenger.of(context).showSnackBar(
                        const SnackBar(content: Text('Giờ kết thúc phải lớn hơn giờ bắt đầu!')),
                      );
                      return;
                    }
                    setState(() {
                      _daySlotsMap[_selectedDay] = (_daySlotsMap[_selectedDay] ?? []) + [
                        DayTimeSlot(
                          id: 'slot_custom_${DateTime.now().millisecondsSinceEpoch}',
                          startTime: startCtrl.text,
                          endTime: endCtrl.text,
                          availableDuration: duration,
                          workouts: [],
                        )
                      ];
                    });
                    Navigator.of(context).pop();
                  }
                }
              },
              style: ElevatedButton.styleFrom(
                backgroundColor: AppTheme.vibrantPrimary,
                foregroundColor: Colors.white,
              ),
              child: const Text('Lưu lại'),
            ),
          ],
        );
      },
    );
  }

  void _showAddWorkoutToSlotDialog(DayTimeSlot slot) {
    final nameCtrl = TextEditingController();
    final durCtrl = TextEditingController(text: '30');
    final formKey = GlobalKey<FormState>();

    showDialog<void>(
      context: context,
      builder: (context) {
        return AlertDialog(
          title: Text('Xếp lịch tập (${slot.startTime} - ${slot.endTime}) 🏃‍♂️', style: const TextStyle(fontWeight: FontWeight.bold, fontSize: 16)),
          content: Form(
            key: formKey,
            child: SingleChildScrollView(
              child: Column(
                mainAxisSize: MainAxisSize.min,
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  const Text('Chọn nhanh bài tập mẫu:', style: TextStyle(fontSize: 11, fontWeight: FontWeight.bold, color: AppTheme.vibrantTextMedium)),
                  const SizedBox(height: 6),
                  Wrap(
                    spacing: 6,
                    runSpacing: 6,
                    children: _presets.map((preset) {
                      final name = preset['name'] as String;
                      final dur = preset['duration'] as int;
                      return ActionChip(
                        label: Text('$name (${dur}p)', style: const TextStyle(fontSize: 10)),
                        padding: EdgeInsets.zero,
                        onPressed: () {
                          nameCtrl.text = name;
                          durCtrl.text = dur.toString();
                        },
                      );
                    }).toList(),
                  ),
                  const SizedBox(height: 12),
                  const Divider(),
                  TextFormField(
                    controller: nameCtrl,
                    decoration: const InputDecoration(labelText: 'Tên bài tập tự nhập'),
                    validator: (v) => v == null || v.isEmpty ? 'Hãy nhập tên bài tập' : null,
                  ),
                  const SizedBox(height: 8),
                  TextFormField(
                    controller: durCtrl,
                    keyboardType: TextInputType.number,
                    decoration: const InputDecoration(labelText: 'Thời gian tập (phút)'),
                    validator: (v) => int.tryParse(v ?? '') == null ? 'Lỗi số phút' : null,
                  ),
                ],
              ),
            ),
          ),
          actions: [
            TextButton(
              onPressed: () => Navigator.of(context).pop(),
              child: const Text('Huỷ', style: TextStyle(color: AppTheme.vibrantTextMedium)),
            ),
            ElevatedButton(
              onPressed: () {
                if (formKey.currentState!.validate()) {
                  final dur = int.parse(durCtrl.text);
                  if (dur > slot.remainingDuration) {
                    ScaffoldMessenger.of(context).showSnackBar(
                      SnackBar(content: Text('Không đủ chỗ trống! (Còn ${slot.remainingDuration}p trống)')),
                    );
                    return;
                  }

                  final newItem = ScheduledWorkoutItem(
                    id: 'w_${DateTime.now().millisecondsSinceEpoch}',
                    name: nameCtrl.text,
                    durationMinutes: dur,
                    caloriesBurned: dur * 6,
                  );

                  setState(() {
                    slot.workouts.add(newItem);
                  });

                  widget.onWorkoutScheduled(
                    WorkoutPlan(
                      id: newItem.id,
                      title: newItem.name,
                      durationMinutes: newItem.durationMinutes,
                      difficulty: 'Custom',
                      equipment: 'None',
                      estimatedCaloriesBurned: newItem.caloriesBurned,
                      exercises: [newItem.name],
                      tags: const [],
                      isScheduled: true,
                    ),
                  );

                  Navigator.of(context).pop();
                }
              },
              style: ElevatedButton.styleFrom(
                backgroundColor: AppTheme.vibrantPrimary,
                foregroundColor: Colors.white,
              ),
              child: const Text('Thêm vào'),
            ),
          ],
        );
      },
    );
  }

  void _showEditWorkoutDialog(DayTimeSlot slot, ScheduledWorkoutItem workout) {
    final nameCtrl = TextEditingController(text: workout.name);
    final durCtrl = TextEditingController(text: workout.durationMinutes.toString());
    final formKey = GlobalKey<FormState>();

    showDialog<void>(
      context: context,
      builder: (context) {
        return AlertDialog(
          title: const Text('Chỉnh sửa bài tập 📝', style: TextStyle(fontWeight: FontWeight.bold)),
          content: Form(
            key: formKey,
            child: Column(
              mainAxisSize: MainAxisSize.min,
              children: [
                TextFormField(
                  controller: nameCtrl,
                  decoration: const InputDecoration(labelText: 'Tên bài tập'),
                  validator: (v) => v == null || v.isEmpty ? 'Hãy nhập tên bài tập' : null,
                ),
                const SizedBox(height: 8),
                TextFormField(
                  controller: durCtrl,
                  keyboardType: TextInputType.number,
                  decoration: const InputDecoration(labelText: 'Thời gian (phút)'),
                  validator: (v) => int.tryParse(v ?? '') == null ? 'Lỗi số phút' : null,
                ),
              ],
            ),
          ),
          actions: [
            TextButton(
              onPressed: () => Navigator.of(context).pop(),
              child: const Text('Huỷ', style: TextStyle(color: AppTheme.vibrantTextMedium)),
            ),
            ElevatedButton(
              onPressed: () {
                if (formKey.currentState!.validate()) {
                  final dur = int.parse(durCtrl.text);
                  final otherWorkouts = slot.workouts.where((w) => w.id != workout.id).fold(0, (sum, w) => sum + w.durationMinutes);
                  final allowed = slot.availableDuration - otherWorkouts;

                  if (dur > allowed) {
                    ScaffoldMessenger.of(context).showSnackBar(
                      SnackBar(content: Text('Vượt quá giờ rảnh! (Cho phép tối đa ${allowed}p)')),
                    );
                    return;
                  }

                  setState(() {
                    final idx = slot.workouts.indexWhere((w) => w.id == workout.id);
                    if (idx != -1) {
                      slot.workouts[idx] = workout.copyWith(
                        name: nameCtrl.text,
                        durationMinutes: dur,
                        caloriesBurned: dur * 6,
                      );
                    }
                  });

                  Navigator.of(context).pop();
                }
              },
              style: ElevatedButton.styleFrom(
                backgroundColor: AppTheme.vibrantPrimary,
                foregroundColor: Colors.white,
              ),
              child: const Text('Lưu thay đổi'),
            ),
          ],
        );
      },
    );
  }

  @override
  Widget build(BuildContext context) {
    final slots = _daySlotsMap[_selectedDay] ?? [];

    return Scaffold(
      appBar: AppBar(
        title: const Text('Lập Lịch Bài Tập 🏋️‍♂️'),
      ),
      body: SafeArea(
        child: ListView(
          padding: const EdgeInsets.symmetric(horizontal: 20, vertical: 8),
          children: [
            const Text(
              'Lập kế hoạch tập luyện tự động & thủ công dựa trên các khe thời gian rảnh rỗi trong tuần.',
              style: TextStyle(fontSize: 12, color: AppTheme.vibrantTextMedium),
            ),
            const SizedBox(height: 16),

            // Weekdays tab strip
            SizedBox(
              height: 40,
              child: ListView.builder(
                scrollDirection: Axis.horizontal,
                itemCount: _weekdays.length,
                itemBuilder: (context, index) {
                  final day = _weekdays[index];
                  final isSelected = day == _selectedDay;
                  return Padding(
                    padding: const EdgeInsets.only(right: 8),
                    child: ChoiceChip(
                      label: Text(day),
                      selected: isSelected,
                      selectedColor: AppTheme.vibrantPrimary,
                      backgroundColor: Colors.white,
                      labelStyle: TextStyle(
                        fontSize: 12,
                        fontWeight: FontWeight.bold,
                        color: isSelected ? Colors.white : AppTheme.vibrantTextMedium,
                      ),
                      shape: RoundedRectangleBorder(
                        borderRadius: BorderRadius.circular(12),
                        side: BorderSide(color: isSelected ? AppTheme.vibrantPrimary : AppTheme.vibrantBorderMedium),
                      ),
                      onSelected: (selected) {
                        if (selected) {
                          setState(() {
                            _selectedDay = day;
                          });
                        }
                      },
                    ),
                  );
                },
              ),
            ),
            const SizedBox(height: 16),

            // Goal setup card
            Card(
              color: Colors.white,
              child: Padding(
                padding: const EdgeInsets.all(16),
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    const Text(
                      'Chỉ Tiêu Vận Động Hằng Ngày 🎯',
                      style: TextStyle(fontSize: 14, fontWeight: FontWeight.bold, color: AppTheme.vibrantTextDark),
                    ),
                    const SizedBox(height: 8),
                    Row(
                      children: [
                        Expanded(
                          child: Column(
                            crossAxisAlignment: CrossAxisAlignment.start,
                            children: [
                              const Text('ĐÃ LÊN LỊCH', style: TextStyle(fontSize: 10, color: AppTheme.vibrantTextLight, fontWeight: FontWeight.bold)),
                              Text('$_totalWorkoutTime / $_minRequiredTime phút', style: const TextStyle(fontSize: 16, fontWeight: FontWeight.bold, color: AppTheme.vibrantTextDark)),
                            ],
                          ),
                        ),
                        Container(
                          decoration: BoxDecoration(
                            color: _isGoalAchieved ? AppTheme.vibrantLightHighlight : AppTheme.vibrantAlertCoral.withOpacity(0.1),
                            borderRadius: BorderRadius.circular(8),
                          ),
                          padding: const EdgeInsets.symmetric(horizontal: 10, vertical: 4),
                          child: Text(
                            _isGoalAchieved ? 'Đạt chỉ tiêu ✨' : 'Chưa đạt ⚠️',
                            style: TextStyle(
                              fontSize: 11,
                              fontWeight: FontWeight.bold,
                              color: _isGoalAchieved ? AppTheme.vibrantPrimary : AppTheme.vibrantAlertCoral,
                            ),
                          ),
                        ),
                      ],
                    ),
                    const SizedBox(height: 12),
                    Slider(
                      value: _minRequiredTime.toDouble(),
                      min: 15,
                      max: 180,
                      divisions: 11,
                      label: '$_minRequiredTime phút',
                      activeColor: AppTheme.vibrantPrimary,
                      inactiveColor: AppTheme.vibrantBorderMedium,
                      onChanged: (v) {
                        setState(() {
                          _minRequiredTime = v.toInt();
                        });
                      },
                    ),
                  ],
                ),
              ),
            ),
            const SizedBox(height: 16),

            // Action Buttons (Auto scheduler & Add new slot)
            Row(
              children: [
                Expanded(
                  child: ElevatedButton.icon(
                    onPressed: _triggerAutoSchedule,
                    icon: const Icon(Icons.rocket_launch, size: 14, color: Colors.white),
                    label: const Text('Xếp lịch tự động 🤖', style: TextStyle(fontSize: 11, fontWeight: FontWeight.bold)),
                    style: ElevatedButton.styleFrom(
                      backgroundColor: AppTheme.vibrantPrimary,
                      foregroundColor: Colors.white,
                      shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(10)),
                      minimumSize: const Size.fromHeight(40),
                    ),
                  ),
                ),
                const SizedBox(width: 8),
                Expanded(
                  child: OutlinedButton.icon(
                    onPressed: _showAddCustomSlotDialog,
                    icon: const Icon(Icons.calendar_today, size: 14, color: AppTheme.vibrantPrimary),
                    label: const Text('Tạo giờ rảnh mới', style: TextStyle(fontSize: 11, fontWeight: FontWeight.bold, color: AppTheme.vibrantPrimary)),
                    style: OutlinedButton.styleFrom(
                      side: const BorderSide(color: AppTheme.vibrantPrimary),
                      shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(10)),
                      minimumSize: const Size.fromHeight(40),
                    ),
                  ),
                ),
              ],
            ),
            const SizedBox(height: 20),

            // Free time slots list today
            Text(
              'Các khung giờ rảnh & bài tập hôm nay ($_selectedDay):',
              style: const TextStyle(fontSize: 13, fontWeight: FontWeight.bold, color: AppTheme.vibrantTextDark),
            ),
            const SizedBox(height: 8),

            if (slots.isEmpty)
              const Center(
                child: Padding(
                  padding: EdgeInsets.symmetric(vertical: 32),
                  child: Text('Không có khung giờ rảnh nào được ghi nhận.', style: TextStyle(color: AppTheme.vibrantTextLight)),
                ),
              )
            else
              Column(
                children: slots.map((slot) {
                  return Card(
                    color: Colors.white,
                    margin: const EdgeInsets.only(bottom: 12),
                    child: Padding(
                      padding: const EdgeInsets.all(16),
                      child: Column(
                        crossAxisAlignment: CrossAxisAlignment.start,
                        children: [
                          Row(
                            mainAxisAlignment: MainAxisAlignment.spaceBetween,
                            children: [
                              Text(
                                'Khung giờ: ${slot.startTime} - ${slot.endTime}',
                                style: const TextStyle(fontSize: 13, fontWeight: FontWeight.bold, color: AppTheme.vibrantSecondary),
                              ),
                              Row(
                                children: [
                                  Text(
                                    'Trống: ${slot.remainingDuration}p / ${slot.availableDuration}p',
                                    style: const TextStyle(fontSize: 11, color: AppTheme.vibrantTextMedium, fontWeight: FontWeight.bold),
                                  ),
                                  const SizedBox(width: 8),
                                  IconButton(
                                    icon: const Icon(Icons.delete_outline, color: AppTheme.vibrantAlertCoral, size: 18),
                                    onPressed: () {
                                      setState(() {
                                        _daySlotsMap[_selectedDay]?.removeWhere((s) => s.id == slot.id);
                                      });
                                    },
                                  )
                                ],
                              )
                            ],
                          ),
                          const Divider(),
                          if (slot.workouts.isEmpty)
                            Padding(
                              padding: const EdgeInsets.symmetric(vertical: 8),
                              child: Row(
                                mainAxisAlignment: MainAxisAlignment.spaceBetween,
                                children: [
                                  const Text('Chưa có lịch tập', style: TextStyle(fontSize: 11, color: AppTheme.vibrantTextLight)),
                                  TextButton.icon(
                                    onPressed: () => _showAddWorkoutToSlotDialog(slot),
                                    icon: const Icon(Icons.add, size: 14),
                                    label: const Text('Thêm bài', style: TextStyle(fontSize: 11)),
                                  )
                                ],
                              ),
                            )
                          else ...[
                            Column(
                              children: slot.workouts.map((w) {
                                return ListTile(
                                  contentPadding: EdgeInsets.zero,
                                  leading: Checkbox(
                                    value: w.isCompleted,
                                    activeColor: AppTheme.vibrantPrimary,
                                    onChanged: (val) {
                                      setState(() {
                                        w.isCompleted = val ?? false;
                                      });
                                      if (w.isCompleted) {
                                        widget.onWorkoutCompleted(
                                          WorkoutPlan(
                                            id: w.id,
                                            title: w.name,
                                            durationMinutes: w.durationMinutes,
                                            difficulty: 'Custom',
                                            equipment: 'None',
                                            estimatedCaloriesBurned: w.caloriesBurned,
                                            exercises: [w.name],
                                            tags: const [],
                                            isScheduled: true,
                                            isCompleted: true,
                                          ),
                                        );
                                      }
                                    },
                                  ),
                                  title: Text(
                                    w.name,
                                    style: TextStyle(
                                      fontSize: 12,
                                      fontWeight: FontWeight.bold,
                                      color: AppTheme.vibrantTextDark,
                                      decoration: w.isCompleted ? TextDecoration.lineThrough : null,
                                    ),
                                  ),
                                  subtitle: Text(
                                    '⏱ ${w.durationMinutes}p | 🔥 ${w.caloriesBurned} kcal ${w.isAutoGenerated ? "| 🤖 Auto" : ""}',
                                    style: const TextStyle(fontSize: 11, color: AppTheme.vibrantTextMedium),
                                  ),
                                  trailing: Row(
                                    mainAxisSize: MainAxisSize.min,
                                    children: [
                                      IconButton(
                                        icon: const Icon(Icons.edit_outlined, size: 16, color: AppTheme.vibrantPrimary),
                                        onPressed: () => _showEditWorkoutDialog(slot, w),
                                      ),
                                      IconButton(
                                        icon: const Icon(Icons.close, size: 16, color: AppTheme.vibrantAlertCoral),
                                        onPressed: () {
                                          setState(() {
                                            slot.workouts.removeWhere((item) => item.id == w.id);
                                          });
                                        },
                                      ),
                                    ],
                                  ),
                                );
                              }).toList(),
                            ),
                            const SizedBox(height: 8),
                            if (slot.remainingDuration > 0)
                              Align(
                                alignment: Alignment.centerRight,
                                child: TextButton.icon(
                                  onPressed: () => _showAddWorkoutToSlotDialog(slot),
                                  icon: const Icon(Icons.add, size: 14),
                                  label: const Text('Thêm bài tập', style: TextStyle(fontSize: 11)),
                                ),
                              ),
                          ]
                        ],
                      ),
                    ),
                  );
                }).toList(),
              ),
            const SizedBox(height: 32),
          ],
        ),
      ),
    );
  }
}
